# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fm.101.camp蟒营®播客/钩陈各种值得探讨
email: zoomquiet+fm@gmail.com
description: "fm.101.camp is PodCasting from 101.camp. 蟒营™101.camp is OpenSource online course framework, the goal is help people design the effective course, the really help learnner effective learnning. But we discover the main problem for learnning is how to clear thinking and asking, so we try usage PodCasting discuss all kinds of things be worth discussion;这是蟒营™101.camp 的电台, 101.camp 是个开源网络课程框架, 目的是帮助人们构建有效课程, 令学习者真正进入学习状态. 在运营过程中我们发现问题最大的问题是: 如何清晰的思考以及提问, 所以, 开始尝试用 PodCasting 形式邀请各种学习者来讨论一切值得讨论的."
subtitle: "A discussion from the 蟒营™101.camp for life & learnning."
lang: zh-cn
author: Zoom.Quiet
copyright: "蟒营®101.camp&#xA9; 2017~2023"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tm.101.camp" # the base hostname & protocol for your site
itunes: "https://podcasts.apple.com/cn/podcast/fm-101-camp-%E8%9F%92%E8%90%A5-%E7%94%B5%E5%8F%B0-%E5%8B%BE%E9%99%88%E5%90%84%E7%A7%8D%E5%80%BC%E5%BE%97%E6%8E%A2%E8%AE%A8/id1499193864"
twitter_username: zoomq
github_username:  zoomquiet

permalink: /:year/:title.html

#Timezone
timezone: China/Shanghai

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

