# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FM.101.camp
email: ask@101.camp
description: "Link Rot is a discussion held at the intersection of life and technology. Each week we dive into a subject that explores the changes going on in digital technology and the way it affects our lives. We discuss how technology impacts our very humanity and aim to have some fun along the way!"
subtitle: "A discussion from the intersection of life & technology."
lang: zh-cn
author: Zoom.Quiet
copyright: "&#xA9; 2020"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tm.101.camp" # the base hostname & protocol for your site
twitter_username: zoomq
github_username:  zoomquiet

permalink: /:year/:title.html

#Timezone
timezone: China/Shanghai

#Setup for Pages
include: ['_pages']

# Build settings
markdown: kramdown

#Exclude local build settings
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

